### ISSUE TITLE
Support delays from gtfs realtime

### ISSUE THREAD

**Issue by tomalikem** [wietlabs/krk_meetings#191]

**Comment by tomekzaw** [comment]
`Downloader.download_merged_data` now returns a tuple of merged data and service ID offset which was to shift `service_id` column of `calendar_df` from `parsed_data_2`.
```py
downloader = Downloader()
merged_data, service_id_offset = downloader.download_merged_data()
```
`service_id_offset` needs to be stored in order to shift `service_id` column in `vehicle_positions_df` accordingly.
```py
vehicle_positions_pb_T, vehicle_positions_pb_A = downloader.download_vehicle_positions()
parser = VehiclePositionsParser()
vehicle_positions_df_T = parser.parse(vehicle_positions_pb_T)
vehicle_positions_df_A = parser.parse(vehicle_positions_pb_A)
vehicle_positions_df_A['service_id'] += service_id_offset
```

**Comment by tomekzaw** [comment]
Currently, `Downloader` first downloads the GTFS Static feeds and then processes the data using hard-wired `Parser` and `Merger`  objects. This approach violates the Single Responsiblity Principle (SRP), because `Downloader` is responsible for both downloading and processing the data. It is advisable to split the pipeline into two separate steps:
1. Downloading
```py
gtfs_zip_T, gtfs_zip_A = self.downloader.download_gtfs_static_data()
```
2. Processing (parsing & merging)
```py
parser = Parser()
parsed_data_T = parser.parse(gtfs_zip_T)
parsed_data_A = parser.parse(gtfs_zip_A)

merger = Merger()
merged_data, service_id_offset = merger.merge(parsed_data_T, parsed_data_A)
```

**Comment by tomekzaw** [comment]
For downloading and parsing GTFS Realtime's VehiclePositions.pb feed, use the following script:
```py
downloader = Downloader()
vehicle_positions_pb_T, vehicle_positions_pb_A = downloader.download_vehicle_positions()

parser = VehiclePositionsParser()
vehicle_positions_df_T = parser.parse(vehicle_positions_pb_T)
vehicle_positions_df_A = parser.parse(vehicle_positions_pb_A)

vehicle_positions_df_A['service_id'] += service_id_offset  # service_id_offset needs stored when updating GTFS Static data
vehicle_positions_df = pd.concat((vehicle_positions_df_T, vehicle_positions_df_A))  # TODO: move to GTFS Realtime Merger
```
Then merge `vehicle_positions_df` and `stop_times_df` with departure times converted to next departure timestamps and subtract `actual_timestamp - planned_timestamp` in order to retrieve delays in seconds.
